### ISSUE TITLE
fix installation error - include 'rethinkdb' in credential.local.yml

### ISSUE THREAD

**Issue by noamoss** [RoySegall/nuntius-bot#97]
![image](https://user-images.githubusercontent.com/3581741/28536905-c3ec3c6c-70b1-11e7-96bd-e7ce2f1b1245.png)

**Comment by noamoss** [comment]
@RoySegall can't assign here, please imagine it was assigned to you.

**Comment by RoySegall** [comment]
Well... Took some time, nearly a year but it solved now. Happy botting dude!
